const char *env_tmpl = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n"
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\"\n"
"    \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n"
"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n"
"<head>\n"
"<meta http-equiv=\"Content-Type\" content=\"application/xhtml+xml; charset=UTF-8\" />\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.7\" />\n"
"<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/format.css\" />\n"
"<title><TMPL_VAR name=\"TITLE\"></title>\n"
"</head>\n"
"<body>\n"
"<table border=\"1\" cellspacing=\"2\" width=\"100%\">\n"
"  <thead>\n"
"  <tr>\n"
"    <td class=\"headingcell\">Name</td>\n"
"    <td class=\"headingcell\">Value</td>\n"
"  </tr>\n"
"  </thead>\n"
"  <tbody><TMPL_LOOP name=\"ENV\">\n"
"  <tr>\n"
"    <td><TMPL_VAR name=\"NAME\"></td>\n"
"    <td><TMPL_VAR name=\"VALUE\"></td>\n"
"  </tr></TMPL_LOOP>\n"
"  </tbody>\n"
"</table>\n"
"</body>\n"
"</html>\n"
;
